---
- name: Reset Kubernetes cluster (if needed)
  command: kubeadm reset --force
  ignore_errors: yes

- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ k8s_master_private_ip }} --ignore-preflight-errors=all
  register: kubeadm_init

- name: Create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy kubeconfig
  shell: |
    sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu

- name: Output join command
  debug:
    msg: "kubeadm join {{ ansible_host }}:6443 --token {{ kubeadm_init.stdout_lines | select('search', 'token') | list | first.split(' ')[1] }} --discovery-token-ca-cert-hash sha256:{{ kubeadm_init.stdout_lines | select('search', 'discovery-token-ca-cert-hash') | list | first.split(' ')[1] }}"

- name: Install Flannel CNI
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
