---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: common
      tags: common

- name: Setup Kubernetes Master
  hosts: master_public
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: master
      tags: master

- name: Setup Kubernetes Worker
  hosts: worker_public
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: worker
      tags: worker
