flowchart TD
  B[GitHub Actions Workflow] --> C[Check ECR Repository]
  C -->|Exists| D[Build Docker Image]
  C -->|"Doesn't Exist"| E[Create ECR Repository]
  D --> F[Push Image to ECR]
  E --> F
  F --> G[ECR Repository with Image]

  subgraph Secrets
    H[GitHub Secrets]
    H --> I[AWS_ACCESS_KEY_ID]
    H --> J[AWS_SECRET_ACCESS_KEY]
    H --> K[AWS_REGION]
    H --> L[AWS_ACCOUNT_ID]
  end

  B --> H
  D --> I
  D --> J
  F --> K
  F --> L

