flowchart TD
  B[GitHub Actions Workflow] -->|GitHub Secrets| C[Check ECR Repository]
  C -->|Exists| D[Build Docker Image]
  C -->|"Doesn't Exist"| E[Create ECR Repository]
  E --> D
  D -->|Push Image to ECR| F[ECR Repository with Image]

